apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: forklift-nonadmin
  namespace: openshift-mtv
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - '*'
- apiGroups:
  - forklift.konveyor.io
#  - v2v.kubevirt.io
  resources:
  - '*'
  verbs:
  - '*'
