apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: m_htaccess_idp 
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: m-htpass-secret